//User Info
export const IS_USER_LOGIN = 'IS_USER_LOGIN';
export const USER_ROLE = 'USER_ROLE';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_TOKEN = 'LOGIN_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const FCM_TOKEN = 'FCM_TOKEN';
export const USER_PROFILE_INFO = 'USER_PROFILE_INFO';

// App
export const APP_MASTER_DATA = 'APP_MASTER_DATA';
export const APP_USERS_DATA = 'APP_USERS_DATA';
export const CLEAR_DATA = 'CLEAR_DATA';
export const EVENT_FILTER_ACTION = 'EVENT_FILTER_STATE';

//State
export const SET_DEVICE_ORIENTATION = 'SET_DEVICE_ORIENTATION';
export const SET_APP_STATE = 'SET_APP_STATE';
export const DEVICE_INFO = 'DEVICE_INFO';
export const REFRESH_SCREEN_BY_NOTIFICATION = 'REFRESH_SCREEN_BY_NOTIFICATION';

//NetInfo
export const SET_CONNECTION_TYPE = 'SET_CONNECTION_TYPE';
export const TOGGLE_CONNECTIVITY = 'TOGGLE_CONNECTIVITY';
